In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("train.csv")

In [3]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
df.dropna(inplace=True)

In [6]:
df.isna().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [7]:
X=df.drop("label",axis=1)

In [8]:
y=df["label"]

In [13]:
X.shape

(18285, 4)

In [15]:
X

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [14]:
y.shape

(18285,)

In [18]:
from tensorflow.keras.layers import Embedding,LSTM,Dense 
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [19]:
voc_size=5000

# Onehot Representation

In [20]:
message=X.copy()

In [21]:
message['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [22]:
message.reset_index(inplace=True)

In [23]:
message['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [25]:
import nltk
from nltk.corpus import stopwords
import re

In [26]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\lohit\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [28]:
#Date preprocessing
from nltk.stem.porter import PorterStemmer

In [31]:
ps=PorterStemmer()
corpus=[]
for i in range(0,len(message)):
    review=re.sub('[^a-zA-Z]',' ',message['title'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [32]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [33]:
#One Hot encoding
onehot_repr=[one_hot(words,voc_size) for words in corpus]

In [37]:
onehot_repr

[[1262, 1645, 4625, 1858, 3360, 2244, 16, 4750, 2063, 1642],
 [1275, 139, 1008, 1547, 1895, 2428, 3633],
 [4300, 1189, 1146, 4132],
 [3459, 967, 2629, 2932, 3641, 1535],
 [3085, 1895, 2331, 3333, 1217, 3443, 1895, 663, 1879, 3752],
 [3551,
  250,
  3234,
  320,
  3223,
  973,
  757,
  3731,
  3148,
  1128,
  1997,
  4910,
  35,
  627,
  3633],
 [1679, 4466, 1245, 2413, 3049, 4555, 3310, 2781, 2419, 3168, 2562],
 [577, 3684, 1702, 1019, 3565, 4908, 973, 3698, 2419, 3168, 2562],
 [3872, 2851, 4439, 2084, 3447, 553, 255, 1006, 973, 4936],
 [1327, 2902, 3802, 2413, 4736, 2230, 2298, 3213],
 [2064, 2011, 3260, 2821, 335, 2940, 4856, 472, 4096, 2102, 441],
 [2932, 4631, 3360, 553, 973, 3565],
 [4875, 4569, 48, 3900, 2973, 4505, 3282, 4165, 515],
 [1544, 3742, 3486, 3841, 1975, 3832, 4623, 2419, 3168, 2562],
 [3588, 1339, 3346, 3834, 500, 2419, 3168, 2562],
 [1352, 3365, 4910, 2877, 1082, 188, 1669, 842, 4331, 232],
 [194, 1525, 139],
 [1029, 94, 564, 3119, 973, 4784, 1025, 3633],
 [1150, 407

# Embedding Representation

In [38]:
sent_lenght=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_lenght)

In [40]:
embedded_docs

array([[   0,    0,    0, ..., 4750, 2063, 1642],
       [   0,    0,    0, ..., 1895, 2428, 3633],
       [   0,    0,    0, ..., 1189, 1146, 4132],
       ...,
       [   0,    0,    0, ..., 2419, 3168, 2562],
       [   0,    0,    0, ..., 1409,  755, 1774],
       [   0,    0,    0, ..., 3398, 4772,   47]])

In [41]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 1262,
       1645, 4625, 1858, 3360, 2244,   16, 4750, 2063, 1642])

In [44]:
from tensorflow.keras import Sequential

In [46]:
#creating model
embedding_vector=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector,input_length=sent_lenght))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [47]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________


In [48]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [49]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [50]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [51]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)


Epoch 1/10
192/192 [==============================] - 12s 35ms/step - loss: 0.4920 - accuracy: 0.7512 - val_loss: 0.1922 - val_accuracy: 0.9176
Epoch 2/10
192/192 [==============================] - 5s 28ms/step - loss: 0.1433 - accuracy: 0.9445 - val_loss: 0.1917 - val_accuracy: 0.9185
Epoch 3/10
192/192 [==============================] - 6s 30ms/step - loss: 0.0917 - accuracy: 0.9656 - val_loss: 0.2217 - val_accuracy: 0.9213
Epoch 4/10
192/192 [==============================] - 5s 28ms/step - loss: 0.0657 - accuracy: 0.9772 - val_loss: 0.2222 - val_accuracy: 0.9203
Epoch 5/10
192/192 [==============================] - 5s 28ms/step - loss: 0.0444 - accuracy: 0.9866 - val_loss: 0.2903 - val_accuracy: 0.9176
Epoch 6/10
192/192 [==============================] - 6s 29ms/step - loss: 0.0228 - accuracy: 0.9933 - val_loss: 0.3424 - val_accuracy: 0.9118
Epoch 7/10
192/192 [==============================] - 5s 28ms/step - loss: 0.0175 - accuracy: 0.9951 - val_loss: 0.3402 - val_accuracy: 0.907

In [52]:
y_pred=model.predict_classes(X_test)

C:\Users\lohit\anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [53]:
from sklearn.metrics import confusion_matrix


In [54]:
confusion_matrix(y_test,y_pred)

array([[3184,  235],
       [ 309, 2307]], dtype=int64)

In [55]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9098591549295775